# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cd0d991756c0e71d49939952481fda9165739a14c0d2792ee0dde6ef01b4b3f6a634012ca86e7608974460ecfc44b89d22e6dba87ba2de423f9615b63a723b4

test:
  secret_key_base: 9815103d3a2ccd0fde78f9ad4362d25632017457a2412c4c867080f43e5018faefe7810fc52061ba021e8aa1f86c442e28af56a63ce3c8363879e382c3c9d8c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
